### ISSUE TITLE
Inconsistent check on group prefix 'keymaker'

### ISSUE THREAD

**Issue by laroo** [kislyuk/keymaker#10]
The functions 'get_groups' and 'sync_groups' uses different prefixes: **underscore** and **dash**
- 'get_groups()' checks on a group prefix that starts with 'keymaker_'
- 'sync_groups()' checks on a group prefix that starts with 'keymaker-' and group path is '/keymaker/'

I currently have both groups included in Amazon IAM to workaround this issue

**Comment by kislyuk** [comment]
Thank you for noticing this. I need an integration test for this but I haven't gotten to the point where I'm comfortable with giving it write access to IAM in the test suite. Should be fixed now.
