### ISSUE TITLE
Install possible without enabling ChallengeResponseAuthentication/keyboard-interactive?

### ISSUE THREAD

**Issue by FutureSharks** [kislyuk/keymaker#23]
Is it required? It would be great if we could leave these disabled.

```
ChallengeResponseAuthentication yes
AuthenticationMethods publickey keyboard-interactive:pam,publickey
```

**Comment by kislyuk** [comment]
Thanks for asking & sorry about the late response. I finally got around to testing this and I no longer see why these settings are necessary. I introduced them when I was originally tuning sshd/PAM for this application, and they don't seem needed in the current configuration, so I removed them from `keymaker configure`.

**Comment by kislyuk** [comment]
Released in v0.5.3.

**Comment by tamsky** [comment]
> Turns out this config is in fact necessary to autovivify users.

Is this a preference, rather than a requirement?

Currently we only auto-vivify groups (via cron, using `sync-groups`),
which forces us to keep
    `keyboard-interactive:pam,publickey`
in the config.

Is there anything preventing us from auto-vivifying both users & groups (again, via cron)?

**Comment by kislyuk** [comment]
By auto-vivify users I mean create the user account on the fly when the
user is first connecting via ssh. If you are fine without that
functionality (you want to sync your users via a cron job and make new
users wait before logging in, for example), then you should be able to turn
off this sshd config line.

**Comment by tamsky** [comment]
> (you want to sync your users via a cron job and make new users wait before logging in...

yes, new IAM users would have to wait for cron to run -- or use another system that triggers that script (eg. SNS, SSM, consul-template).

I was hoping to hear from you, @kislyuk, (and anyone else who wants to chime in),
what your design ideas and concerns were around the current design of only having a
`sync_groups` command — and no `sync_users` command?

A `sync_users` command would seem to offer a choice to anyone wishing to avoid the additional risk of a `keyboard-interactive` `AuthenticationMethod`.

Would you be amenable to an implementation of a `sync_users` command via a PR?

**Comment by kislyuk** [comment]
@tamsky - if you want an alternative user account sync method that is triggered via cron, and an option to `keymaker install` to configure it, I'd be happy to accept a PR for it.

**Comment by maxcountryman** [comment]
@tamsky did you end up working on this?

**Comment by tamsky** [comment]
Not yet.

**Comment by maxcountryman** [comment]
@tamsky I put together a [hacky prototype](https://github.com/maxcountryman/keymaker/commit/e96b5ebbfacf1ab94eeec078dbf957488c148e1b) of this which seems to work for my use-case.

@kislyuk Not sure how you feel about this--would you be interested in this if it were cleaned up?

**Comment by tamsky** [comment]
LGTM, comments posted on your branch.
