### ISSUE TITLE
Feature request: Multi-account managment

### ISSUE THREAD

**Issue by benjaminpottier** [kislyuk/keymaker#27]
I wrote a hack for your application to allow me to manage iam user access in a top level account as opposed to always referencing the account associated with the instance. Have you considered adding this at all?

**Comment by kislyuk** [comment]
I'm certainly interested in adding this. How would you imagine this working? How would you communicate configuration information about the linked accounts to the keymaker daemon?

**Comment by kislyuk** [comment]
(We have discussed a similar concept for federated accounts at work as well, and couldn't come up with an elegant solution, but we didn't brainstorm it much)

**Comment by benjaminpottier** [comment]
I don't know. I'm not by any stretch of the imagination a programmer but I really liked your program so I just quickly wrote a function to make it work.

[kaymaker_hack.py.zip](https://github.com/kislyuk/keymaker/files/1540151/kaymaker_hack.py.zip)

**Comment by kislyuk** [comment]
Fixed in #29.
