### ISSUE TITLE
how is it supposed to work if keymaker-create-account-for-iam-user always fails

### ISSUE THREAD

**Issue by myster-t** [kislyuk/keymaker#28]
I'm a bit confused as to how `keymaker-create-account-for-iam-user` signals success to PAM. When i first create an account, the script exists with `EX_TEMPFAIL` or 75 and the error output says I have to try again. Then when I try again, it fails with `EX_NOPERM` or 77. And all I see on the client side (trying to ssh in) is:

```
/usr/local/bin/keymaker-create-account-for-iam-user failed: exit code 77

/usr/local/bin/keymaker-create-account-for-iam-user failed: exit code 77

/usr/local/bin/keymaker-create-account-for-iam-user failed: exit code 77

Permission denied (publickey,keyboard-interactive).
```

What am I missing here?

**Comment by kislyuk** [comment]
EX_NOPERM simply means that all authentication methods have failed, and the user's account already exists or does not need creating. This means that earlier in the login process, the user failed to be authenticated using their SSH key.

Did you upload the user's SSH public key to their IAM account? And are you using that key (ssh -i) when trying to log in?

**Comment by myster-t** [comment]
that was the problem. i was using the wrong private key. thanks!!
