### ISSUE TITLE
federated access

### ISSUE THREAD

**Issue by bpottier** [kislyuk/keymaker#34]
I'm confused by this paragraph:

_Run the following command in the ID resolver account (that contains the IAM users) to apply this configuration automatically: keymaker configure --instance-iam-role arn:aws:iam::987654321098:role/ROLE_NAME --cross-account-profile AWS_CLI_PROFILE_NAME._ 

In our environment we aren't running any instances in the "resolver account". We're just storing IAM users there for access to resources in child accounts. So how would keymaker be made to work in this situation? I apologize if I'm just missing something obvious. Thanks!

**Comment by kislyuk** [comment]
Correct, you're not expected to be running any instances in the ID resolver account, but you do need to configure the IAM role that the instances will be running with for cross-account access. This command performs that configuration for you, in particular by writing the Keymaker configuration into the role description. You can also do it manually.

**Comment by bpottier** [comment]
Still not clear to me ... I have the keymaker_id_resolver_account set to the account number where I have my iam users. The keymaker_id_resolver_role is the role in that account that has the iam permissions for listing public keys, etc. That all goes into the description of the role associated with the instance running keymaker and that role has permissions to do an sts:assumerole on the resolver account role. Is that right?

**Comment by kislyuk** [comment]
Correct. That's the configuration that `keymaker configure` is expected to apply automatically.

**Comment by bpottier** [comment]
ok. In my example, what exactly would the keymaker configure command line arguments be?

**Comment by kislyuk** [comment]
`keymaker configure --instance-iam-role arn:aws:iam::987654321098:role/ROLE_NAME --cross-account-profile AWS_CLI_PROFILE_NAME`
Run this as an IAM user logged in to your parent account, with an AWS CLI profile for cross-account access (to the account with EC2 instances) configured under the alias AWS_CLI_PROFILE_NAME.

**Comment by kislyuk** [comment]
Closing. If you have suggested improvements to the docs, please open a PR.
