### ISSUE TITLE
Sudo access?

### ISSUE THREAD

**Issue by jeremymturner** [kislyuk/keymaker#35]
Looks great! I was able to test successfully on an Ubuntu EC2 instance.

One feature I am looking to have is sudo access. One thought would be:
1. If user is a member of group ssh-sudoers, we create /etc/sudoers.d/<username> and not prompt them for a password, since they do not have one.
2. If user is a member of group ssh-users, the keymaker works as it does today.

Today, it would help me just to have #1, give all users sudo access.

**Comment by kislyuk** [comment]
If you look at https://github.com/kislyuk/keymaker#principle-of-operation, it mentions a system for synchronizing IAM group membership with Unix group membership. The specific IAM group that you need to create and add the user to in this case is `keymaker_sudo`. This should add the user to the Unix group `sudo`, which on Ubuntu grants sudo privileges.

**Comment by jeremymturner** [comment]
Ahh... you are so kind. I deserved an RTFM for that. Thanks so much and great work on this!

**Comment by kislyuk** [comment]
You're welcome, let me know if you find any bugs with this solution.
