### ISSUE TITLE
Mismatch between docs and code for keymaker_id_resolver_role

### ISSUE THREAD

**Issue by renaudhager** [kislyuk/keymaker#36]
Hi,

Thanks for your work :-)

I tried to setup cross account authentication, I followed the documentation and added this to the description of the IAM role configured on the instance profile : 
```
keymaker_id_resolver_account=11111111111
keymaker_id_resolver_role=test-ssh
```

But I got the following error : 
```
root@ip-10-104-52-43:/etc/pam.d# /usr/sbin/keymaker-get-public-keys user1
Traceback (most recent call last):
  File "/usr/local/bin/keymaker", line 125, in <module>
    locals()[args.command](args)
  File "/usr/local/lib/python2.7/dist-packages/keymaker/__init__.py", line 133, in get_authorized_keys
    resource="role/" + config["keymaker_id_resolver_iam_role"])
KeyError: u'keymaker_id_resolver_iam_role'
```

After a quick look to the code, it appears that the key : `keymaker_id_resolver_role` is not used.
I fixed the issue by updating the role description using `keymaker_id_resolver_iam_role` instead of keymaker_id_resolver_role.

I think the documentation should be updated  to avoid any confusion.

Cheers,

Renaud Hager

**Comment by kislyuk** [comment]
Thank you for reporting!

This should be fixed in master now.
