### ISSUE TITLE
keymaker get_uid is not working when cross account auth is configured.

### ISSUE THREAD

**Issue by renaudhager** [kislyuk/keymaker#37]
Hi,

I come across the following issue : when I use keymaker with cross account auth enable, function `keymaker get_uid` is not working.
 I got the following error : 
```
root@ip-10-104-52-43:/etc/pam.d# keymaker get_uid myuser
Error while retrieving UID for mysuer: An error occurred (NoSuchEntity) when calling the GetUser operation: The user with name myuser cannot be found.
root@ip-10-104-52-43:/etc/pam.d#
```

After looking the code the following function `get_uid` always instantiate iam.resource from the current account (where the EC2 instance is running). It should instantiate iam.resource on the resolver account.

I fixed the code locally, I'll submit PR for review.

**Comment by renaudhager** [comment]
Also fixed the  get_group function.

**Comment by kislyuk** [comment]
Thanks for the report. This should be fixed now.
