### ISSUE TITLE
Group sync broken in 0.5.2

### ISSUE THREAD

**Issue by rscottthreewiresyscom** [kislyuk/keymaker#40]
When I run sync_groups I get an error when using 0.5.2:
local variable 'iam_linux_group_prefix' referenced before assignment

I have confirmed that if I revert to 0.5.1 it works correctly.
Environment:
  - RHEL 7.4 AND CentOS 7.4
  - Python 2.7.5

[rscott@ip-10-100-1-1 ~]$ /usr/bin/keymaker sync_groups
WARNING:keymaker:u'Description'
Traceback (most recent call last):
  File "/usr/bin/keymaker", line 127, in <module>
    locals()[args.command](args)
  File "/usr/lib/python2.7/site-packages/keymaker/__init__.py", line 387, in sync_groups
    if not group.name.startswith(iam_linux_group_prefix):
UnboundLocalError: local variable 'iam_linux_group_prefix' referenced before assignment

**Comment by kislyuk** [comment]
Thank you for reporting this. Fixed in v0.5.3.
