### ISSUE TITLE
Superuser required?

### ISSUE THREAD

**Issue by maxcountryman** [kislyuk/keymaker#54]
Apologies if I overlooked this in the documentation, but I'm curious if running as root is a requirement for keymaker?

**Comment by kislyuk** [comment]
The answer depends on what you mean by "running keymaker".

- To install keymaker into the sshd config and crontab (`keymaker install`), you need access to those daemons' config files, which normally means you need root access.
- The keymaker authorization hook (runs when sshd logs you in) does not need root access.
- None of the client-side functionality (commands listed under https://github.com/kislyuk/keymaker#usage) need root access.

**Comment by maxcountryman** [comment]
Perfect--thanks for explanation!
