### ISSUE TITLE
keymaker-create-account-for-iam-user path incompatible with pam.d/sshd config

### ISSUE THREAD

**Issue by thisdougb** [kislyuk/keymaker#56]
I am using the AWS AMI ami-0fbac225f3afdf632 (eu-central-1, Amazon Linux 2, ECS optimised, etc).  The file keymaker-create-account-for-iam-user is installed in /usr/bin by pip. However the pam.d/sshd configuration created by Keymaker (pam_config_line) looks for it in /usr/local/bin.

Workaround is a symlink, created after installing Keymaker:
```
# yum install -y python2-pip 
# pip install keymaker
# keymaker install
# type keymaker-create-account-for-iam-user 
keymaker-create-account-for-iam-user is /usr/bin/keymaker-create-account-for-iam-user
# ln -s /usr/bin/keymaker-create-account-for-iam-user /usr/local/bin/keymaker-create-account-for-iam-user
```
but out of the box it's not working.

**Comment by kislyuk** [comment]
Thanks for reporting! Yes, this is definitely a bug. `/usr/local/bin` should not be hardcoded but instead inferred at install time.

**Comment by thisdougb** [comment]
@kislyuk want me to do a PR, a function along these lines?  There's two places the '/usr/local/bin' is hardcoded.

```
import os

# do we need a default, could this avoid breaking some OS's ?
keymaker_create_account_for_iam_user_path = '/usr/local/bin/keymaker-create-account-for-iam-user'

if 'PATH' in os.environ:
  for p in os.environ['PATH'].split(':'):
    testPath = "{0}/{1}".format(p, "keymaker-create-account-for-iam-user")
    if os.path.isfile(testPath):
      keymaker_create_account_for_iam_user_path = os.path.abspath(testPath)

pam_config_line = "auth optional pam_exec.so stdout {0}".format(keymaker_
```create_account_for_iam_user_path)

print(pam_config_line)
